### ISSUE TITLE
TickBasedTime#setCurrentTick(double) throws UnsupportedOperationException

### ISSUE THREAD

**Issue by p76dub** [fmichel/MaDKit#4]
Hi !

I have found an issue in `Scheduler.TickBasedTime`. I was trying to reset the simulation time in a tick-based simulation. To do so, I used `Scheduler.SimulationTime#setCurrentTick(double)` operation but I got an `UnsupportedOperationException`.

It turns out that contrary to what the documentation says, it is not a "shortcut of `setCurrentTick(BigDecimal.valueOf(value))`". I would have expected something like this as the body:

```java
public default void setCurrentTick(double value){
    return setCurrentTick(BigDecimal.valueOf(value));
}
```

Since it is not the case, it is not enough to override `setCurrentTick(BigDecimal)` to have `setCurrentTick(double value)` working. Unfortunately, `Scheduler.TickBasedTime` only overrides the BigDecimal version :(

I switched back to the BigDecimal version in my code but could be great to fix it ;)

Best regards
Pierre

**Comment by fmichel** [comment]
Hi Pierre,

Thanks for pointing out this omission with all the provided details
It is fixed.

Best,
Fabien
