### ISSUE TITLE
Multiple schedulers sharing the same simulation time

### ISSUE THREAD

**Issue by p76dub** [fmichel/MaDKit#5]
Hi,
My colleagues and I are currently developing an application on top of Madkit and we have questions about having multiple schedulers in the same simulation.

### Context

For now we have a working simulation with several agents and a customized scheduler. Each agent "schedules" a bunch of actions at each tick. To do so, we created a custom `ActionActivator`, which is an activator that rather executing a method on all agents in a CGR location, executes an action (one activator per action).

The problem we are facing is that only the scheduler is executing the actions, decreasing performances (agents threads are idle).

If I understand well the threading model of Madkit:
- one thread per agent
- the activation of a behavior with an `Activator` can be distributed on several threads

The first point is fine when you have concurrent agents working at different speed, the second is designed for tick/date-based simulations. We can of course mix both.

### Problem

To address our performance issue, we came up with several ideas:
1. Use the `Activator#useMulticore` capability. Unfortunately, given the fact that each activator executes only one action, we won't be able to distribute it.
2. Modify our action execution process: rather than scheduling actions on the scheduler, each agent manages its own actions. Then the scheduler send "top" messages to all agents, which execute scheduled actions for the current tick. This solution is good, but requires a bit of work to address agent synchronization.
3. Rather than having one scheduler, we could have multiple schedulers (up to one per regular agent). This solution could avoid us rewriting the action execution process, **but is it feasible with Madkit ?** I mean of course we can deploy several schedulers, but will they be synchronized ? Can they share a global simulation time ?

Thanks a lot for your time !
Pierre

**Comment by fmichel** [comment]
Hi,
Sorry for the delayed answer.
First, to be sure that I correctly understand, when designing simulation, you should extend the AbstractAgent class to avoid having one thread per Agent : AbstractAgent instances are not threaded (they are designed to be scheduled in a simulation), while Agent ones are.
Apart from that, it is indeed possible to use a hierarchical scheduling with one "master" scheduler controlling slave schedulers sharing the same simulation time (initialized upon creation by the master scheduler). 
Still, having one scheduler per agent looks like non optimal and should be probably done another way.
Do not hesitate if this answer is incomplete or fuzzy considering your use case.

Best,
Fabien

**Comment by p76dub** [comment]
Hi !

Thanks for the detailed answer. I wasn't aware of the difference between `AbstractAgent` and `Agent` but it is crystal clear now. We agreed on mixing hierarchical schedulers and distributed action execution using the Madkit service executor. It seems to work so far !

Thanks again for your time
Pierre
